name: Testnet Deployment

on:
  push:
    tags:
      - "*"

concurrency:
  group: "testnet-deployment"
  cancel-in-progress: false

env:
  RPC_URL: ${{ secrets.RPC_URL }}
  OPG_URL: ${{ secrets.OPG_URL }}
  OPS_URL: ${{ secrets.OPS_URL }}
  XMTP_L3_URL: ${{ secrets.XMTP_L3_URL }}
  PRIVATE_KEY: ${{ secrets.PRIVATE_KEY }}
  ETHERSCAN_API_KEY: ${{ secrets.ETHERSCAN_API_KEY }}
  SEPOLIA_PROXY_ADDRESS: "0x15aE865d0645816d8EEAB0b7496fdd24227d1801"
  OP_GOERLI_PROXY_ADDRESS: "0x146Aa237567bEAa52C51570D2A2BC8150C63754B"
  OP_SEPOLIA_PROXY_ADDRESS: "0xAaCe07B4C163D2bCcA78237E1F863b6d20122762"
  XMTP_L3_PROXY_ADDRESS: "0xDcef550E7bd54018d86f63877b1E6B019682a1c0"
  RELEASE_TAG: ${{ github.ref_name }}

jobs:
  check:
    strategy:
      fail-fast: true

    name: xps-contract
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          submodules: recursive

      - name: Install Foundry
        uses: foundry-rs/foundry-toolchain@v1
        with:
          version: nightly-fca0a6c5ed3576a692c2444ec459e0ee5321e3e5

      - name: Yarn install
        run: |
          yarn install --dev
          yarn prettier:check
          yarn lint
          yarn install --production

      - name: Run Forge tests
        run: |
          forge test -v --fail-fast
        id: test

      - name: XMTP Arbitrum L3
        run: |
          echo "Upgrade ${XMTP_L3_PROXY_ADDRESS} to ${RELEASE_TAG}"
          PROXY_ADDRESS=${XMTP_L3_PROXY_ADDRESS} forge script ./script/DeployConversation.s.sol:DeployConversation --sig 'upgrade()' -g 150 --slow --broadcast --rpc-url ${XMTP_L3_URL} --private-key ${PRIVATE_KEY}
