name: Testnet Deployment

on:
  push:
    tags:
      - "*"

concurrency:
  group: "testnet-deployment"
  cancel-in-progress: false

env:
  RPC_URL: ${{ secrets.RPC_URL }}
  OPS_URL: ${{ secrets.OPS_URL }}
  ARS_URL: ${{ secrets.ARS_URL }}
  PRIVATE_KEY: ${{ secrets.PRIVATE_KEY }}
  ETHERSCAN_API_KEY: ${{ secrets.ETHERSCAN_API_KEY }}
  SEPOLIA_PROXY_ADDRESS: "0xD58349485CA7cdFabD8fD9ACb0855E6644f22600"
  ARB_SEPOLIA_PROXY_ADDRESS: "0xD58349485CA7cdFabD8fD9ACb0855E6644f22600"
  OP_SEPOLIA_PROXY_ADDRESS: "0xD58349485CA7cdFabD8fD9ACb0855E6644f22600"
  RELEASE_TAG: ${{ github.ref_name }}

jobs:
  check:
    strategy:
      fail-fast: true

    name: xps-contract
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          submodules: recursive

      - name: Install Foundry
        uses: foundry-rs/foundry-toolchain@v1
        with:
          version: nightly

      - name: Yarn install
        run: |
          yarn install --dev
          yarn prettier:check
          yarn lint
          yarn install --production

      - name: Run Forge tests
        run: |
          forge test -v --fail-fast
        id: test

      - name: Sepolia
        run: |
          echo "Upgrade ${SEPOLIA_PROXY_ADDRESS} to ${RELEASE_TAG}"
          PROXY_ADDRESS=${SEPOLIA_PROXY_ADDRESS} forge script ./script/DeployConversation.s.sol:DeployConversation --sig 'upgrade()' --slow --broadcast --rpc-url ${RPC_URL} --private-key ${PRIVATE_KEY} --etherscan-api-key ${ETHERSCAN_API_KEY} --verify

      - name: OP Sepolia
        run: |
          echo "Upgrade ${OP_SEPOLIA_PROXY_ADDRESS} to ${RELEASE_TAG}"
          PROXY_ADDRESS=${OP_SEPOLIA_PROXY_ADDRESS} forge script ./script/DeployConversation.s.sol:DeployConversation --sig 'upgrade()' --slow --broadcast --rpc-url ${OPS_URL} --private-key ${PRIVATE_KEY}

      - name: ARB Sepolia
        run: |
          echo "Upgrade ${ARB_SEPOLIA_PROXY_ADDRESS} to ${RELEASE_TAG}"
          PROXY_ADDRESS=${ARB_SEPOLIA_PROXY_ADDRESS} forge script ./script/DeployConversation.s.sol:DeployConversation --sig 'upgrade()' -g200 --slow --broadcast --rpc-url ${ARS_URL} --private-key ${PRIVATE_KEY}

      - name: GitHub Release
        uses: actions/create-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          draft: false
          prerelease: false
          tag_name: ${{ github.ref_name }}
          release_name: ${{ github.ref_name }}
          body_path: CHANGELOG.md
